from pathlib import Path
from typing import TYPE_CHECKING

from qtpy.QtCore import Signal
from qtpy.QtWidgets import QPushButton, QWidget

if TYPE_CHECKING:
    import napari

def get_barcode() -> str: ...
def find_most_commonprefix_name(folder: Path, name: str) -> str: ...

class WormTracerUI(QWidget):
    def __init__(self, viewer: napari.Viewer, parent=None) -> None: ...
    def _move_frame(self, step: int) -> None: ...
    def _save_all(self) -> None: ...
    def _load_centerline(self) -> None: ...
    def _reload_centerline(self) -> None: ...
    def _load_image(self) -> None: ...
    def _register(self) -> None: ...
    def _flip(self) -> None: ...
    def _reset_centerline(self) -> None: ...
    def _undo(self) -> None: ...
    def _update_color(self, color: str, target_shape: str) -> None: ...

class ColorButton(QPushButton):
    """
    Custom Qt Widget to show a chosen color.

    Left-clicking the button shows the color-chooser, while
    right-clicking resets the color to None (no-color).
    """

    colorChanged: Signal

    def __init__(self, parent, *args, color=None, **kwargs) -> None: ...
    @property
    def contrast_color(self) -> str | None: ...
    def setColor(self, color: str): ...
    def color(self) -> str: ...
    def onColorPicker(self) -> None: ...
    def mousePressEvent(self, e): ...
