from typing import TYPE_CHECKING

from qtpy.QtWidgets import QWidget

if TYPE_CHECKING:
    import napari

class WormTracerUI(QWidget):
    def __init__(self, viewer: napari.Viewer, parent=None) -> None: ...
    def _move_frame(self, step: int) -> None: ...
    def _save_all(self) -> None: ...
    def _load_centerline(self) -> None: ...
    def _reload_centerline(self) -> None: ...
    def _load_image(self) -> None: ...
    def _register(self) -> None: ...
    def _flip(self) -> None: ...
    def _reset_centerline(self) -> None: ...
    def _undo(self) -> None: ...
